### ISSUE TITLE
BUG Transfer Filter

### ISSUE THREAD

**Issue by viniotero** [mz-ir/mazyar#105]
Hi, after the last update, i can't create more transfer filter. I created 2 more here, and always shows X. But if you filter in market, you can find the players. Just a feedback

**Comment by mz-ir** [comment]
you must check at least one of H and L check-boxes **before** saving the filter. Otherwise it is **not considered** 'Scout' filter and it is just a normal filter.

![image](https://github.com/user-attachments/assets/7be88494-2705-4a0a-a95a-8c0280c73966)


For normal filters, column 'Scout' will be marked with 'X'.

![image](https://github.com/user-attachments/assets/79876648-6cf3-4c59-9c5b-2d8b244c9494)
